export default {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    LOGOUT: 'LOGOUT',

    UPDATE_USER_STATUS: "UPDATE_USER_STATUS",
    UPDATE_USER: "UPDATE_USER",
};
